### ISSUE TITLE
String Scalar functions

### ISSUE THREAD

**Issue by tigermatos** [RioDB/riodb#31]
We need scalar functions similar to these from MySQL:

https://ramkedem.com/en/mysql-scalar-functions/

STEPS:  
1) the name of the function has to be all lower-case. words separated by underscore.   
2) Add function declaration in:  src/org/riodb/sql/SQLScalarFunctionsReturningString  
3) Add function name to array in src/org/riodb/sql/SQLScalarFunctions.  

For example, see concat function that already exists in the file.  

Hint: If the function takes String as input, we may need to check that the input is not null.

**Comment by Th7mo** [comment]
Hi!
Which scalar functions do you want to have implented for `String`s?

**Comment by RioDB** [comment]
Hi @th7mo  
Thank you and sorry for the late response. Traveling.  How about:
String upper(String s)  
String lower(String s)  
String replace(String s, String old, String new)  
String substr(String s, int from)  
String substr(String s, int from, int to)  
--  
If s is null, it can return null. If substr int is out of bounds, it can raise exception.  
Fastest way to communicate with the team is on our discord server.  
https://discord.gg/FbjRHstSkV  
Thanks!!!

**Comment by th7mo** [comment]
Hi @RioDB, I implemented the methods and will make a Pull Request now, the only thing I needed to modify was the declaration of `String replace(String s, String old, String new)`, since the word `new` can't be used as parameter name. This is because the name `new` is a reserved keyword of Java. I renamed `old` to `old_s` and `new` to `new_s`
